// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	DeleteMetadata(ctx context.Context, key string) error
	// Metadata operations for database identification and sync state
	GetMetadata(ctx context.Context, key string) (string, error)
	ListMetadata(ctx context.Context) ([]Metadata, error)
	SetMetadata(ctx context.Context, arg SetMetadataParams) error
}

var _ Querier = (*Queries)(nil)
